Repository Day-Walk/MLOps, pull requests merged in 2025-06, with the labels that each got.

#10 Feature/es search
  ELK/Dockerfile
  ELK/app/__init__.py
  ELK/app/main.py
  ELK/app/schema/__init__.py
  ELK/app/schema/search_schemas.py
  ELK/app/services/__init__.py
  ELK/app/services/elasticsearch_service.py
  ELK/docker-compose.yml
  ELK/requirements.txt
  MLOps/Dockerfile
  MLOps/app/__init__.py
  MLOps/app/main.py
  MLOps/app/model/deepfm_model.py
  MLOps/app/schema/__init__.py
  MLOps/app/schema/recommendation_schema.py
  MLOps/app/services/__init__.py
  MLOps/app/services/deepctr_service.py
  MLOps/app/services/elk_client.py
  MLOps/app/services/user_data_service.py
  MLOps/docker-compose.yml
  MLOps/main.py
  MLOps/requirements.txt
  data/src/py_es_place_upload.py
  data/src/test.ipynb
  data/src/utils/es_place_upload.py
  start_all.sh
Labels: ✨ Feature

#12 refactor: 검색엔진 및 추천시스템 API 코드 수정 및 리팩토링
  MLOps/app/main.py
  MLOps/app/schema/recommendation_schema.py
  MLOps/app/services/deepctr_service.py
  MLOps/app/services/user_data_service.py
  start_all.sh
Labels: 🔨 Refactor

#15 chore: EC2 ELK 서버 compose 정의
  ELK/Dockerfile
  ELK/docker-compose.yml
  ELK/requirements.txt
Labels: ⚙ Setting

#18 Refactor/장소 데이터 api 리팩토링
  data/src/place_api.py
Labels: 🔨 Refactor

#22 chore: ELK docker-compose 파일 수정
  ELK/docker-compose.yml
Labels: 🌏 Deploy

#27 Chore: docker compose ip 변경
  MLOps/docker-compose.yml
Labels: 🌏 Deploy

#33 Feat/챗봇 초기 모델 및 api
  MLOps/requirements.txt
Labels: ⚙ Setting

#35 chore: dvc s3 설정 및 json 파일 1개 테스트
  .dvc/config
  MLOps/.gitignore
  MLOps/test.txt
  data/PLACES_DATA_V4_2_20250613.json.dvc
Labels: ⚙ Setting

#36 chore: dvc config 수정
  .dvc/config
Labels: ⚙ Setting

#38 fix: Elasticsearch 연결 호스트 수정 및 헬스체크 엔드포인트 추가
  ELK/app/main.py
  ELK/app/services/elasticsearch_service.py
Labels: 🐞 BugFix

#40 fix: 절대 경로 설정
  ELK/app/main.py
Labels: 🐞 BugFix

#41 fix: 절대 경로 설정
  ELK/app/main.py
Labels: 🐞 BugFix

#44 fix: 오탈자 수정
  ELK/docker-compose.yml
Labels: 🐞 BugFix

#46 fix: pydantic 문법 오류 수정 및 인덱스 이름 수정
  ELK/app/schema/search_schemas.py
  ELK/app/services/elasticsearch_service.py
Labels: 🐞 BugFix

#47 v1.1.4
  ELK/app/schema/search_schemas.py
  ELK/app/services/elasticsearch_service.py
Labels: 🐞 BugFix

#48 fix: pydantic 오류 수정
  ELK/app/services/elasticsearch_service.py
Labels: 🐞 BugFix

#49 v1.1.5
  ELK/app/services/elasticsearch_service.py
Labels: 🐞 BugFix

#52 Feat/챗봇 초기 모델 및 api
  MLOps/app/services/deepctr_service.py
  MLOps/app/services/elk_client.py
  MLOps/app/services/user_data_service.py
  data/.gitignore
  data/chroma_db_bge.dvc
Labels: 🐞 BugFix, ✨ Feature

#54 Feat/챗봇 초기 모델 및 api
  .github/workflows/Deploy-ML-EC2.yml
  MLOps/app/main.py
  MLOps/app/model/deepfm_model.pt.dvc
  MLOps/app/model/deepfm_train.py
  MLOps/app/model/key2index.pkl.dvc
  MLOps/app/model/label_encoders.pkl.dvc
  MLOps/app/routers/chatbot.py
  MLOps/app/routers/recommendation.py
  MLOps/app/schema/chat_schema.py
  MLOps/app/schema/recommendation_schema.py
  MLOps/app/services/deepctr_service.py
  MLOps/app/services/elk_client.py
  MLOps/app/services/openai_service.py
  MLOps/app/services/place_extractor.py
  MLOps/app/services/user_data_service.py
  MLOps/requirements.txt
  data/final_click_log.csv.dvc
  data/user.csv.dvc
Labels: ✨ Feature

#56 chore: pip 업그레이드 추가
  MLOps/Dockerfile
Labels: 🐞 BugFix

#57 배포 v1.2.1
  MLOps/Dockerfile
Labels: 🌏 Deploy

#58 chore: requirements.txt에서 torch 관련 패키지 버전 수정
  MLOps/requirements.txt
Labels: 🐞 BugFix

#59 배포 v1.2.2
  MLOps/requirements.txt
Labels: 🌏 Deploy

#61 배포 v1.2.3
  .github/workflows/Deploy-ML-EC2.yml
  MLOps/app/routers/recommendation.py
  MLOps/app/schema/recommendation_schema.py
  MLOps/app/services/deepctr_service.py
Labels: 🌏 Deploy

#64 배포 v1.2.4
  MLOps/requirements.txt
Labels: 🐞 BugFix, 🌏 Deploy

#65 배포 v1.2.5
  .github/workflows/Deploy-ML-EC2.yml
Labels: 🌏 Deploy

#67 배포 v1.2.6
  MLOps/app/services/deepctr_service.py
  MLOps/app/services/user_data_service.py
Labels: 🐞 BugFix, 🌏 Deploy

#72 chore: requirements.txt에 OpenAI 라이브러리 추가
  MLOps/requirements.txt
Labels: 🐞 BugFix

#76 chore: docker-compose.yml에 OPENAI_API_KEY 환경 변수 추가
  MLOps/docker-compose.yml
Labels: 🐞 BugFix

#77 fix: DeepFMModdelTrain 클래스의 모델 경로를 상대 경로로 수정
  MLOps/app/model/deepfm_train.py
Labels: 🐞 BugFix

#85 feat: 사용자별 로그 검색 기능 개선
  ELK/app/services/elasticsearch_service.py
Labels: ✨ Feature

#87 feat: 로그 스키마에 위치 정보 추가 및 Elasticsearch 매핑 수정
  ELK/app/schema/log_schemas.py
  ELK/app/services/elasticsearch_service.py
Labels: ✨ Feature

#91 fix: 사용자 데이터 경로 변경 및 사용자 정보 조회 기능 수정
  MLOps/app/services/user_data_service.py
Labels: 🐞 BugFix

#99 feat: db 접근 및 유저 데이터 사용
  MLOps/app/services/db_connection.py
  MLOps/requirements.txt
  data/user_db.json.dvc
  data/user_like_db.json.dvc
Labels: ✨ Feature

#100 feat: LLM 도구를 위한 장소 검색 API의 카테고리 길이 제한 수정
  ELK/app/main.py
Labels: ✨ Feature

#107 feat: 챗봇 에이전트의 데이트 코스 추천 로직 및 도구 사용 규칙 업데이트
  MLOps/app/services/chatbot_agent_service.py
Labels: ✨ Feature

#111 feat: 사용자 쿼리 기반 필터링 로직과 JSON 응답 처리 방식 업데이트
  MLOps/app/services/chatbot_agent_service.py
Labels: ✨ Feature

#114 feat: 챗봇 에이전트의 OpenAI 함수 에이전트에 대한 새로운 프롬프트 템플릿 추가 및 JSON 응답 처리 개선
  MLOps/app/services/chatbot_agent_service.py
Labels: ✨ Feature

#118 fix: ChatbotAgentService의 임베딩 모델 장치 설정을 CPU로 변경
  MLOps/app/services/chatbot_agent_service.py
Labels: 🐞 BugFix

#120 fix: 챗봇 에이전트의 응답 처리 로직 수정 및 에러 핸들링 추가
  MLOps/app/routers/chatbot.py
Labels: 🐞 BugFix

#124 feat: 챗봇 에이전트의 장소 추천 로직에 사용자의 원래 입력 메시지를 필터링 도구에 포함하도록 규칙 추가
  MLOps/app/services/chatbot_agent_service.py
Labels: ✨ Feature

#130 Feat/langchain agent chatbot
  MLOps/Dockerfile
  MLOps/app/services/chatbot_agent_service.py
  data/chroma_db_bge.dvc
Labels: 🐞 BugFix

#132 fix: ChatbotAgentService에서 검색 결과를 장소 목록으로 반환하도록 수정
  MLOps/app/services/chatbot_agent_service.py
Labels: 🐞 BugFix

#134 fix: ChatbotAgentService에서 검색 결과가 없을 경우 필터 없이 다시 검색하도록 로직 수정 및 반환 형식 개선
  MLOps/app/services/chatbot_agent_service.py
Labels: 🐞 BugFix

#136 Feat/langchain agent chatbot
  MLOps/app/services/chatbot_agent_service.py
Labels: 🐞 BugFix

#138 fix: ChatbotAgentService의 응답 형식을 일관되게 수정
  MLOps/app/routers/chatbot.py
  MLOps/app/services/chatbot_agent_service.py
Labels: 🐞 BugFix

#142 fix: 챗봇 응답 처리 로직을 개선
  MLOps/app/routers/chatbot.py
  MLOps/app/schema/chat_schema.py
  MLOps/app/services/chatbot_agent_service.py
Labels: 🐞 BugFix

#145 Feat/langchain agent chatbot
  MLOps/app/routers/chatbot.py
  MLOps/app/services/langchain_agent_service.py
Labels: ✨ Feature

#149 배포 v1.5.0
  .github/workflows/Deploy-ML-EC2.yml
Labels: 🐞 BugFix

#160 fix: chat log 저장 형식 수정 - title 삭제
  ELK/app/schema/log_schemas.py
Labels: 🐞 BugFix

#164 Feat/혼잡도 api 생성
  .github/workflows/Deploy-ML-EC2.yml
  MLOps/app/main.py
  MLOps/app/model/deepfm_train.py
  MLOps/app/routers/crowd.py
  MLOps/app/schema/crowd_schema.py
  MLOps/app/services/deepctr_service.py
  MLOps/app/services/user_data_service.py
Labels: ✨ Feature

#167 feat: 혼잡도 예측 API 엔드포인트 및 상태 정보 추가
  MLOps/app/main.py
  MLOps/app/routers/crowd.py
Labels: ✨ Feature

#171 refactor: 혼잡도 예측 데이터 전처리 코드 추가
  data/congestion_preprocessing.py
Labels: 🔨 Refactor

#173 Fix/챗봇 출력 형식 버그 수정
  .github/workflows/Deploy-ML-EC2.yml
  MLOps/.env.example
  MLOps/app/services/langchain_agent_service.py
Labels: 🐞 BugFix

#176 feat: 검색 로그 인덱스 생성 및 사용자 검색 로그 기록 기능 추가
  ELK/app/main.py
  ELK/app/services/elasticsearch_service.py
Labels: ✨ Feature

#178 Feat/es 검색 결과 저장
  ELK/app/services/elasticsearch_service.py
  ELK/scripts/generate_dummy_data.py
Labels: ✨ Feature

#185 Feat/deepfm user train
  .github/workflows/ELK_deploy.yml
  ELK/app/services/elasticsearch_service.py
  ELK/docker-compose.yml
  ELK/requirements.txt
  MLOps/app/model/deepfm_model.pt.dvc
  MLOps/app/model/deepfm_train.py
  MLOps/app/model/key2index.pkl.dvc
  MLOps/app/model/label_encoders.pkl.dvc
  MLOps/app/routers/recommendation.py
  MLOps/app/services/db_connection.py
  MLOps/app/services/deepctr_service.py
  MLOps/app/services/openai_service.py
  MLOps/app/services/place_extractor.py
  MLOps/app/services/user_data_service.py
Labels: ✨ Feature

#191 Fix/crowd api 수정
  MLOps/app/services/deepctr_service.py
  start_all.sh
Labels: 🐞 BugFix

#194 Fix/crowd api 수정
  MLOps/app/routers/crowd.py
  MLOps/app/services/langchain_agent_service.py
Labels: 🐞 BugFix

#205 fix: Docker 배포 프로세스를 개선하여 컨테이너를 빌드하고 백그라운드에서 실행하도록 수정
  .github/workflows/Deploy-ML-EC2.yml
Labels: 🐞 BugFix

#207 fix: docker-compose.yml에서 환경 변수 파일 경로를 수정하여 .env 파일을 사용하도록 변경
  MLOps/docker-compose.yml
Labels: 🐞 BugFix

#209 fix: Deploy-ML-EC2.yml에서 데이터베이스 관련 환경 변수를 추가하여 배포 설정 개선
  .github/workflows/Deploy-ML-EC2.yml
Labels: 🐞 BugFix

#213 fix: Deploy-ML-EC2.yml에 데이터베이스 관련 환경 변수를 추가하여 배포 설정을 더욱 개선함
  .github/workflows/Deploy-ML-EC2.yml
Labels: 🐞 BugFix

#218 fix: scikit-learn 버전 변경 (1.7.0 -> 1.3.0)
  MLOps/requirements.txt
Labels: 🐞 BugFix

#220 Fix/챗봇 버그 수정
  MLOps/Dockerfile
  MLOps/app/routers/chatbot.py
  MLOps/app/services/langchain_agent_service.py
  data/chroma_db_bge.dvc
Labels: 🐞 BugFix

#236 feat: Docker Compose 파일에 서울 시간대 환경 변수 추가
  MLOps/docker-compose.yml
Labels: ✨ Feature

#238 Feat/혼잡도 api 내부 로직 구현
  MLOps/app/python_schedule/data/crowd_prediction.dvc
  MLOps/app/services/predict_cong_service.py
  MLOps/docker-compose.yml
Labels: 🐞 BugFix

#241 Feat/es 검색엔진 고도화
  ELK/app/services/elasticsearch_service.py
  data/src/utils/es_place_upload.py
Labels: ✨ Feature

#243 feat: Elasticsearch 검색 쿼리의 가중치 조정
  ELK/app/services/elasticsearch_service.py
Labels: ✨ Feature

#246 fix: 로그 데이터의 타임스탬프를 서울 시간대로 변경
  ELK/app/main.py
  ELK/app/services/elasticsearch_service.py
Labels: 🐞 BugFix

#249 Feat/챗봇 프롬프트 수정
  MLOps/app/services/langchain_agent_service.py
Labels: ✨ Feature

#254 fix: LangchainAgentService의 장소 설명 형식 및 추가 규칙 업데이트
  MLOps/app/services/langchain_agent_service.py
Labels: 🐞 BugFix

#267 fix: Dockerfile에 libgomp1 패키지 설치 추가
  MLOps/Dockerfile
Labels: 🐞 BugFix

#268 fix: Dockerfile에서 libgomp1 패키지 설치 방법 수정
  MLOps/Dockerfile
Labels: 🐞 BugFix

#271 fix: predict_cong_service.py에서 모델 예측 시 feature 이름 가져오는 방법 수정
  MLOps/app/services/predict_cong_service.py
Labels: 🐞 BugFix

#275 Feat/most click place api
  ELK/app/main.py
  ELK/app/schema/search_schemas.py
  ELK/app/services/elasticsearch_service.py
  ELK/scripts/transform_utc_to_kst.py
Labels: ✨ Feature

#279 Feat/챗봇 혼잡도 안내 추가
  MLOps/app/routers/crowd.py
  MLOps/app/services/langchain_agent_service.py
  data/chroma_db_bge.dvc
Labels: ✨ Feature

#281 feat: 장소 검색 기능 개선 및 카테고리 필터링 로직 추가
  ELK/app/services/elasticsearch_service.py
Labels: ✨ Feature

#288 Feat/혼잡도 s3 변경
  .github/workflows/Deploy-ML-EC2.yml
Labels: ✨ Feature

#291 Feat/챗봇 혼잡도 툴 추가
  MLOps/app/routers/crowd.py
  MLOps/app/services/langchain_agent_service.py
Labels: ✨ Feature

#295 feat: 클릭 수 집계 로직 개선 및 시간 범위 수정
  ELK/app/services/elasticsearch_service.py
Labels: ✨ Feature

#297 fix: 혼잡도 예보 텍스트 포맷 수정 - 마크다운 삭제
  MLOps/app/services/langchain_agent_service.py
Labels: 🐞 BugFix
